### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by k80w** [pteromys/svgs2ttf#1]
Howdy, this project doesn't seem to have a license listed, and I'd love to use this tool in my project. Could you please add a license? <3

**Comment by pteromys** [comment]
Ok, reading up on licenses now... would GPLv3 be ok for you? Since it's basically a wrapper over fontforge, that looked like the most sensible option.

This is not to put any restrictions on the files created with it. (I didn't think that was ever done, and enforceability looks questionable, though apparently some IDE licenses try: https://softwareengineering.stackexchange.com/questions/278285/licensing-of-content-created-by-licensed-code )

**Comment by pteromys** [comment]
Added LICENSE file marking it as GPLv3 in 7015be7c11927917a39089afeb69e5d085cf0a4e. Closing the issue for now but please reopen or something if that doesn't meet your needs!
