### ISSUE TITLE
i want to import .jpg file in font forge as glyph? kindly help in this matter.

### ISSUE THREAD

**Issue by preetibhatt29** [pteromys/svgs2ttf#2]

**Comment by pteromys** [comment]
If you want to turn the .jpg into a .svg first, try this tutorial on the Inkscape website:

https://inkscape.org/doc/tutorials/tracing/tutorial-tracing.html

You'll need to download inkscape, import the jpg (file -> import), and then fiddle with the tracing settings until you get results you like.

(Closing the issue since this isn't a bug report/feature request/whatever, but I think it'll still let you comment if you need more help.)
